"""empty message

Revision ID: 4158bb0a7bf3
Revises: 4831dae4f74d
Create Date: 2022-11-22 22:39:35.412291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4158bb0a7bf3'
down_revision = '4831dae4f74d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id_producto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('categoria', sa.String(length=250), nullable=True),
    sa.Column('serie', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.drop_table('producto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto',
    sa.Column('id_producto', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('categoria', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('serie', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_producto', name='producto_pkey')
    )
    op.drop_table('productos')
    # ### end Alembic commands ###
